name: CI/CD for Spring Boot with Maven OpenAI bike repair assistant

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4    
      with:
        sparse-checkout: |
          .github
          backend
          # repository: Hack9_2024_AI-Co-Pilots/backend
          # path: backend
          # sparse-checkout: '/home/runner/work/Hack9_2024_AI-Co-Pilots/Hack9_2024_AI-Co-Pilots/backend'
          # sparse-checkout-cone-mode: false

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '21'

    - name: Build with Maven
      run: mvn clean package

    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: packaged-application
        path: target/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: packaged-application
        path: target/

    - name: Setup key
      id: setup-key
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      run: |
        echo "$DEPLOY_KEY" >> $HOME/key.pem
        chmod 400 $HOME/key.pem

    - name: Copy JAR to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ubuntu
        key: ${{ secrets.DEPLOY_KEY }}
        source: "target/*.jar"
        target: "/home/ubuntu/deployment/"

    - name: Connect SSH and Restart Services
      run: |
        ssh -o StrictHostKeyChecking=no -i $HOME/key.pem ubuntu@ec2-18-170-77-199.eu-west-2.compute.amazonaws.com '
          sudo systemctl restart openai &&
          sudo systemctl restart nginx
        '
